version: '3.9'

networks:
  net:
    driver: bridge

services:
  cdbembed:
    image: cdbembed
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEFAULT_MODEL=all-MiniLM-L6-v2
      - OLLAMA_URL=http://localhost:11434
      - OLLAMA_MODEL=llama2
    restart: unless-stopped 
    expose:
      - "8000"
    ports:
      - "8000:8000"
